branches:
  - master
notifications:
  slack: hackerrank:UFH5hQpL74v4SyALVy3ykoBq
language: node_js
node_js:
  - '8'
before_install:
  - sudo pip install awscli
script:
  - yarn build
  - yarn deploy
after_success: node build/bin.js --config
